version: "3.7"
services:
  static_eol:
    image: static_eol
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./static_eol:/srv/jekyll
    command: jekyll serve --watch --force_polling --incremental --drafts --host 0.0.0.0 --port 4000
